//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentosG
    {
        public int id { get; set; }
        public int Año { get; set; }
        public string Departamento_Origen { get; set; }
        public string Departamento_Destino { get; set; }
        public string Secuencia { get; set; }
        public int idDepa { get; set; }
        public int idUser { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
